channels:
- pytorch
- defaults
dependencies:
- _libgcc_mutex
- _openmp_mutex
- absl-py
- aiohttp
- aiosignal
- async-timeout
- asynctest
- attrs
- blas
- blinker
- brotli
- brotlipy
- c-ares
- ca-certificates
- cachetools
- certifi
- cffi
- charset-normalizer
- click
- cloudpickle
- cryptography
- cudatoolkit
- cycler
- cytoolz
- dask-core
- dataclasses
- dbus
- expat
- fontconfig
- fonttools
- freetype
- frozenlist
- fsspec
- giflib
- glib
- google-auth
- google-auth-oauthlib
- grpcio
- gst-plugins-base
- gstreamer
- icu
- idna
- imageio
- importlib-metadata
- intel-openmp
- jpeg
- kiwisolver
- lcms2
- ld_impl_linux-64
- libffi
- libgcc-ng
- libgfortran-ng
- libgfortran4
- libgomp
- libpng
- libprotobuf
- libstdcxx-ng
- libtiff
- libuuid
- libwebp
- libwebp-base
- libxcb
- libxml2
- locket
- lz4-c
- markdown
- matplotlib
- matplotlib-base
- mkl
- mkl-service
- mkl_fft
- mkl_random
- multidict
- munkres
- ncurses
- networkx
- ninja
- numpy
- numpy-base
- oauthlib
- openssl
- packaging
- partd
- pcre
- pillow
- pip
- protobuf
- pyasn1
- pyasn1-modules
- pycparser
- pyjwt
- pyopenssl
- pyqt
- pysocks
- python==3.8
- python-dateutil
- pytorch
- pywavelets
- qt
- readline
- requests
- requests-oauthlib
- rsa
- scikit-image
- scipy
- setuptools
- sip
- six
- sqlite
- tensorboard
- tensorboard-data-server
- tensorboard-plugin-wit
- tk
- toolz
- torchvision
- tornado
- typing-extensions
- typing_extensions
- urllib3
- werkzeug
- wheel
- xz
- yaml
- yarl
- zipp
- zlib
- zstd
- pip:
  - pandas
  - addict
  - mmcv-full
  - opencv-python
  - pyparsing
  - pyyaml
  - tqdm
  - yapf
  - loguru
name: e2fgvi_test
